#!/bin/bash
# Layered world: empty ground (roads follow our graph) + separate building sprites for y-sorted depth.
P="$(cd "$(dirname "$0")/.." && pwd)"; cd $P/assets/raw
until grep -q ALLDONE gen.log; do sleep 20; done
run() { out=$1; shift; prompt=$1; shift
  [ -s $out ] && return
  codex exec --skip-git-repo-check -s workspace-write -C $P/assets/raw "Use your image generation tool to create ONE NEW image (never reuse an existing file) and save it as $P/assets/raw/$out. $prompt After saving, reply only with the file path." "$@" < /dev/null > $out.log 2>&1
  echo "$out rc=$? $(md5sum $out 2>/dev/null | cut -c1-8)" >> gen.log; }
run ground.png "1536x1024 landscape GAME GROUND LAYER for a 2D RPG overworld, strict top-down 3/4 view like a tile map, edge to edge terrain, NO buildings, NO characters, NO text, NO sky or clouds. Follow the attached LAYOUT GUIDE exactly: the grey lines are cobblestone ROADS (keep their exact positions and widths), the tan ovals are open paved PLAZAS (stone squares with small details: cracks, moss, a few barrels at edges), the blue area is sea with a shoreline and a wooden pier near the harbor plaza. Everything else is grass with flower patches, dirt patches and small rocks; near the VOLCANO plaza the ground turns to dark ash with lava cracks; near FOREST plaza dense grass and fallen leaves; near TOWER and OBSERVATORY light snow dusting. Pixel-art HD-2D palette matching the attached style reference, crisp, even daylight." -i layout-guide.png -i world-bg.png
run buildings.png "1536x1024 BUILDING SPRITE SHEET, TRANSPARENT background, pixel-art HD-2D style matching the attached style reference, top-down 3/4 view (same camera as an RPG overworld). Follow the attached template: 4 columns x 3 rows of 384x341 cells; each cell holds ONE standalone building whose base sits on the red baseline, centered, no ground tile around it except a thin footprint shadow. Cells in order: royal castle with blue roofs and flags; blacksmith forge with chimney, furnace glow and anvil; elven treehouse on a giant tree; purple wizard tower with crystals; star observatory dome with telescope; white holy cathedral with gold spires; dark volcanic fortress gate with chains; steampunk harbor warehouse with crane and a small airship moored above; cozy timber inn with sign; stone gold vault entrance with treasure and griffin statues; stone fountain; cluster of three pine trees. No text, no grid lines, no characters." -i building-template.png -i world-bg.png
echo LAYERSDONE >> gen.log
