#!/bin/bash
# One new character design per (class, model) used by the team: 16-frame sheet (walk8, idle4, attack4).
P="$(cd "$(dirname "$0")/.." && pwd)"; cd $P/assets/raw
declare -A ROLE=([warrior]="sword-and-armour warrior (melee, longsword)" [ranger]="archer ranger (longbow, quiver)" [paladin]="holy paladin (heavy armour, shield and mace)" [engineer]="field engineer (goggles, big wrench, tool belt, small gadget)" [mage]="wizard (tall hat or hood, staff, casts orbs)" [sage]="sage scholar (long robe, nature staff, floating book)" [commander]="army commander (long coat, cape, baton, medals)")
declare -A STYLE=([Sol]="SOL style: sun-forged, warm gold and orange plate/cloth, sun emblem, flame-edged trims, confident heroic look" [Luna]="LUNA style: moonlit, silver and pale blue, crescent-moon motifs, flowing translucent cloth, calm ethereal look" [Sonnet]="SONNET style: arcane scholar-knight, deep violet and indigo with glowing rune engravings, elegant tailored silhouette" [Opus]="OPUS style: legendary archangel, white and gold ornate gear, filigree, small feather details, majestic look" [Haiku]="HAIKU style: swift and minimal, light cyan and white, short scarf, light gear, nimble ninja-like silhouette" [Gemini]="GEMINI style: twin-storm, electric yellow and teal, lightning-bolt motifs, asymmetric twin accents")
for combo in $(cat combos.txt); do
  c=${combo%-*}; m=${combo#*-}; out=combo-$combo.png; [ -s $out ] && continue
  codex exec --skip-git-repo-check -s workspace-write -C $P/assets/raw "Use your image generation tool to create ONE NEW image (never reuse an existing file) and save it as $P/assets/raw/$out. 1536x1024 SPRITE SHEET, TRANSPARENT background, chibi HD pixel-art with the same proportions, camera and level of detail as the attached reference character sheet, but a NEW CHARACTER DESIGN: a ${ROLE[$c]} in ${STYLE[$m]}. Distinct face, hair and outfit from the reference; keep the same role silhouette and weapon type. Follow the attached template EXACTLY: 4x4 cells of 384x256, the SAME character at the SAME size in every cell, facing RIGHT, full body, feet on the red baseline, body centred on the blue line. Row 1-2: one smooth 8-frame walk cycle (right contact, down, passing, up, left contact, down, passing, up), arms and cloth swinging opposite to legs. Row 3: 4-frame idle breathing. Row 4: 4-frame attack (anticipation wind-up, swing/cast/shot, impact with a small effect, recover). No grid lines, baseline, centre line or text." -i combo-template.png -i walk8-$c.png < /dev/null > $out.log 2>&1
  echo "$out rc=$?" >> gen.log
done
echo COMBODONE >> gen.log
